spring:
   application:
      name: SoulArt

   datasource:
      url: jdbc:h2:mem:soulArtDB
      driver-class-name: org.h2.Driver
      username: root
      password: root 
   
   h2:
      console:
         enabled: true

   jpa:
      hibernate:
         ddl-auto: create-drop
         show-sql: true
      properties:
         hibernate:
            dialect: org.hibernate.dialect.H2Dialect
      defer-datasource-initialization: true

logging:
   level:
      root: INFO
      com.art.main: DEBUG
      org.springframework.web: ERROR